#! /bin/bash
# This is the launch script for the nitrogen cycle app
# on unix systems

# make sure we're running from the directory where the script is located
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
cd "$DIR"

Rscript -e "library(shiny); runApp('.', launch.browser = TRUE);"
